version: '3.8'

services:
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipeline
    volumes:
      - ./pipeline:/app/src
    env_file:
      - .env
    depends_on:
      - postgresql

  dbt-job:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipeline
    volumes:
      - ./dbt:/app/app/dbt
    env_file:
      - .env
    depends_on:
      - postgresql


  postgresql:
    image: postgres:13
    container_name: postgresql
    ports:
      - "5435:5435"
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    command: >
      postgres
        -c listen_addresses=*
        -c logging_collector=on
        -c log_destination=stderr
        -c max_connections=200
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 15s
      timeout: 15s
      retries: 5

